"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
$hostname\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$time\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_grey = '#c7c8cc'
color_bg3 = '#665c54'
color_blue = '#4585d8'
color_green = '#81a263'
color_orange = '#dd6d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#fdde55'
color_white = '#fbf1c7'

[hostname]
format = '[$ssh_symbol ](fg:color_blue)[$hostname:](fg:color_blue)'

[username]
show_always = true
style_user = "fg:color_purple"
style_root = "fg:color_purple"
format = '[$user ]($style)'

[directory]
style = "fg:color_blue"
format = "[$path ]($style)"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:color_yellow"
format = '[[$symbol $branch ](fg:color_yellow)]($style)'

[git_status]
style = "fg:color_yellow"
format = '[[($all_status$ahead_behind )](fg:color_yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[$symbol( $version) ](fg:color_white)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[$symbol( $version) ](fg:color_white)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_white)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[$symbol( $version) ](fg:color_white)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[$symbol( $version) ](fg:color_white)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[$symbol( $version) ](fg:color_white)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[$symbol( $version) ](fg:color_white)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[$symbol( $version) ](fg:color_white)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[$symbol( $version) ](fg:color_white)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[$symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:color_grey"
format = '[[ $time ](fg:color_grey)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

