[[plugins]]
repository = 'kana/vim-smartinput'
insert = 1

[[plugins]]
repository = 'Shougo/neocomplete.vim'
insert = 1

[[plugins]]
repository = 'Shougo/vimfiler'
depends = 'Shougo/unite.vim'
commands = [ 'VimFilerTab', 'VimFiler', 'VimFilerExplorer' ]
mappings = '<Plug>(vimfiler_switch)'
explorer = 1

[[plugins]]
repository = 'thinca/vim-quickrun'
mappings = '<Plug>(quickrun)'

[[plugins]]
repository = 'vim-scripts/Align'
commands = 'Align'

[[plugins]]
repository = 'vim-scripts/buftabs.git'
filetypes = 'all'

[[plugins]]
repository = 'thinca/vim-template'
insert = 1

[[plugins]]
repository = 'majutsushi/tagbar'
commands = 'TagbarToggle'

[[plugins]]
repository = 'Shougo/unite.vim'

    [plugin.commands]
    name = 'Unite'
    complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'h1mesuke/unite-outline'
unite_sources = 'outline'

[[plugins]]
repository = 'Shougo/neomru.vim'
filetypes = 'all'

[[plugins]]
repository = 'tpope/vim-surround'
insert = 1

[[plugins]]
repository = 'mattn/zencoding-vim'
filetypes = 'html'

[[plugins]]
repository = 'vim-jp/vimdoc-ja'
filetypes = 'help'

[[plugins]]
repository = 'cespare/vim-toml'
filetypes = 'toml'

[[plugins]]
repository = 'plasticboy/vim-markdown'
filetypes = 'markdown'

[[plugins]]
repository = 'fatih/vim-go'
filetypes = 'go'

[[plugins]]
repository = 'othree/yajs.vim'
filetypes = 'javascript'

[[plugins]]
repository = 'othree/es.next.syntax.vim'
filetypes = 'javascript'

[[plugins]]
repository = 'othree/javascript-libraries-syntax.vim'
filetypes = 'javascript'

[[plugins]]
repository = 'digitaltoad/vim-pug'
filetypes = 'pug'

#[[plugins]]
#repository = 'vim-scripts/YankRing.vim'
#commands = 'YRShow'

#[[plugins]]
#repository = 'Shougo/neosnippet.vim'
#depends = 'honza/vim-snippets'
#insert = 1

#[[plugins]]
#repository = 'davidhalter/jedi-vim'
#filetypes = ['python', 'python3', 'djangohtml']
#build = 'pip install jedi'

